config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get "posts/about"
  get 'users/show'
  devise_for :users
  resources :users, :only => [:show] do
  end

  resources :posts, except: :destroy do

    collection do
      get "index_complete"
      get "index_uncomplete"
    end

    member do
      patch "complete"
      post "/review_create" => "posts#review_create"
    end

  end

  root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_users
  has_many :users, through: :post_users
  has_many :reviews

  validates :title, presence: true
  validates :body, presence: true

  paginates_per 4
end

app/models/post_user.rb
class PostUser < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post_users
  has_many :posts, through: :post_users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name ])
  end

  def authenticate_admin_user!
    authenticate_user!

    # current_userはdevise提供のメソッドです。
    # 権限ユーザのroleについては、好きな方法でよいです。（自分の場合、has_roleメソッドで実装）
    unless current_user.has_role 'admin'
      flash[:alert] = "管理者用ページです。権限があるアカウントでログインしてください。"
      redirect_to root_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :complete]
  before_action :authenticate_user!, only: [:edit, :create, :update, :new, :complete, :review_create, :show ]

  def index
  end

  def show
    @review = Review.new
  end

  def about
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      @post_user = PostUser.new(post_id: @post.id, user_id: current_user.id)
      @post_user.save
      redirect_to index_uncomplete_posts_path
    else
      flash.now[:alert] = @post.errors.full_messages
      render :new
    end
  end

  def edit
  end


  def complete
    @post.update(completed: true)
    redirect_to index_complete_posts_path
  end

  def index_complete
    @posts = Post.where(completed: true).order(created_at: :desc).page(params[:page]).per(4)
  end

  def index_uncomplete
    @posts = Post.where(completed: false).order(created_at: :desc).page(params[:page]).per(4)
  end

  def update
    @post_new = Post.new(post_params)
    if @post.update(body: @post.body + @post_new.body)
      @post_users = PostUser.find_or_create_by(post_id: @post.id, user_id: current_user.id)
      redirect_to @post
    else
      flash.now[:alert] = @post.errors.full_messages
      render :show
    end
  end

  def review_create
  @review = Review.new(review_params)
    if @review.save
      redirect_to post_path(@review.post)
    else
      redirect_to post_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def review_params
    params.require(:review).permit(:body, :post_id, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header ">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Babel", root_path, class: "navbar-brand" %>
          <%= link_to image_tag('/header_logo.png', :class => "header_logo", :alt => 'ホーム'), root_path %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-menu">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "使い方", "/posts/about" %></li>
            <% if user_signed_in? %>
              <li><%= link_to current_user.name, users_show_path %></li>
              <li><%= link_to "設定変更", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <body>
    <div class="container">
       　<div class="row">
          <% if notice.present? %>
            <div class="alert alert-dismissable alert-success">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <p><%= notice %></p>
            </div>
          <% end %>
          <% if alert.present? %>
            <div class="alert alert-dismissable alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <p><%= alert %></p>
            </div>
          <% end %>
         <%= yield %>
       　</div>
     　</div>
  </body>
</html>

app/views/posts/_new_review.html.erb
<div class="col-md-12">
  <%= form_with(model: @review, local: true, url: "/posts/#{@post.id}/review_create") do |form| %>
    <% if review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="field">
      <p><% form.label :body %></p>
      <%= form.text_area :body, id: :review_body %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/posts/about.html.erb
<h1>Babelの使い方</h1>
  <p>Babelは連歌・リレー小説アプリです</p>
  <p>自分、あるいは他の人が書き始めた作品（プロジェクト）の続きを書いていくことでみんなで一つの作品を作ることができます</p>
  <br>
  <h2>ログインしていない場合</h2>
    <p>新規ユーザー登録は<%= link_to "こちら", new_user_registration_path %></p>
    <p>すでにアカウントをお持ちの方は<%= link_to "こちら", new_user_session_path  %></p>
  <br>
  <h2>ログインしている場合</h2>
    <p>ログインしている場合は新規プロジェクトの作成、進行中のプロジェクトの編集、レビューの投稿ができます</p>
  <h3>投稿・編集方法</h3>
    <p>①「新規プロジェクト」でタイトルと本文を入力すると「進行中のプロジェクト」に送信されます</p>
    <p>②そこに他の人のプロジェクトをふくめた進行中のプロジェクトが一覧で並んでいます</p>
    <p>その中で自分が続きを描きたいものをクリックします</p>
    <p>③開くとタイトル、本文と「続きを書く」、「完成！」ボタンが出てきます</p>
    <p>「続きを書く」を押すとそれまでの続きから自分が文章を書くことができます。</p>
    <p>「完成！」を押すとプロジェクトは「終了したプロジェクト」に送信され、閲覧のみできるようになります</p>
  <h3>レビュー機能について</h3>
    <p>投稿詳細ページを開くと本文の下にレビュー一覧とレビュー投稿があります</p>
    <p>プロジェクトについての感想や批評、ユーザー同士のコミュニケーションなど幅広く使ってください</p>
    <p>※他人への誹謗中傷、その他他人を不快にさせる内容は書き込まないようにお願いします</p>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h1>プロジェクト更新</h1>
  <h2>タイトル</h2>
    <%= @post.title %>
  <h2>本文</h2>
    <%= simple_format(@post.body) %>
    <%= form_with model: @post, local: true do |form| %>
      <div class="form-group">
        <%= form.label " " %>
        <br>
        <%= form.text_area :body, value: "", class: "input-mysize2" %>
      </div>
        <%= form.submit '更新する', data: { confirm: "更新しますか？" }, class: "btn btn-primary" %>
    <% end %>
</div>

app/views/posts/index.html.erb
<body>
<div class="col-md-12">
  <div class="target">
    <h1>Babel</h1>
    <h2>連歌・リレー小説アプリ</h2>
      <ul>
        <p><%= link_to "進行中のプロジェクト", index_uncomplete_posts_path %></p>
        <p><%= link_to "終了したプロジェクト", index_complete_posts_path %></p>
        <p><%= link_to "新規プロジェクト", new_post_path %></p>
      </ul>
  </div>
</div>
</body>

app/views/posts/index_complete.html.erb
<div class="col-md-12">
  <h1>終了したプロジェクト一覧</h1>
  <% @posts.each do |post| %>
    <div class="article">
      <h3>タイトル：<%= post.title %></h3>
      <p>作成日：<%= post.created_at %></p>
      <p>作成者：<% post.post_users.each do |post_user| %><%= post_user.user.name %> <% end %></p>
      <p><%= truncate(post.body, length: 50) %></p>
      <p><%= link_to "続きを読む", post, class: "btn btn-default" %></p>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/index_uncomplete.html.erb
<div class="col-md-12">
 <h1>進行中のプロジェクト一覧</h1>
  <% @posts.each do |post| %>
    <div class="article">
      <h3>タイトル：<%= post.title %></h3>
      <p>作成日：<%= post.created_at %></p>
      <p>作成者：<% post.post_users.each do |post_user| %><%= post_user.user.name %> <% end %></p>
      <p>本文：<%= truncate(post.body, length: 50) %></p>
      <p><%= link_to "続きを読む", post, class: "btn btn-default" %></p>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="col-md-12">
  <h1>記事を投稿する</h1>
  <br>
  <%= form_with model: @post, local: true do |form| %>
    <div class="form-group">
      <%= form.label "タイトル" %><br>
      <%= form.text_field :title, class: "input-mysize" %>
    </div>
    <div class="form-group">
      <%= form.label "本文" %><br>
      <%= form.text_area :body, class: "input-mysize2" %>
    </div>
    <%= form.submit '登録する', data: { confirm: "登録しますか？" }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <h1><%= @post.title %></h1>
  <p>投稿日:<%= @post.created_at %></p>
  <br>
  <p>本文</p>
  <%= simple_format(@post.body) %>
</div>
<% if current_user %>
  <% if @post.completed  == false %>
    <%= link_to "続きを書く", edit_post_path(@post), class: "btn btn-default"%>
    <%= link_to "完成！", complete_post_path(@post), method: :patch, class: "btn btn-default"%>
  <% end %>
<% end %>
<br>
<h3>レビュー一覧</h3>
<% @post.reviews.each do |review| %>
  <p>ユーザー名：<%= review.user.name %></p>
  <p><%= review.body %></p>
  <p><%= review.created_at %></p>
  <br>
<% end %>

<h3>レビュー投稿</h3>
<%= render partial: 'new_review', locals: { review: @post.reviews.new } %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>マイページ</h2>
    <h3>名前:<%= @user.name %></h3>
    <br>
    <h3>自分が関わったプロジェクト</h3>
    <% @posts.each do |post| %>
      <div class="article">
        <h3>タイトル：<%= post.title %></h3>
        <p>作成日：<%= post.created_at %></p>
        <p><%= truncate(post.body, length: 50) %></p>
        <p><%= link_to "続きを読む", post, class: "btn btn-default" %></p>
      </div>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>